---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"
      timezone: ${{ secrets.USER_TIMEZONE }}
    labels:
      - "github-actions dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:00"
      timezone: ${{ secrets.USER_TIMEZONE }}
    labels:
      - "docker dependencies"
